server:
  port: 8090


spring:
  application:
    name: msvc-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prueba-microservicio
<<<<<<< HEAD
    username: postgre
=======
    username: postgres
>>>>>>> feature/user-service
    password: Alejandro1996nal
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
